GET http://localhost:3000/users/kamaltest@gmail.com
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAxOTE4Mjk4LCJleHAiOjE2MDE5MjE4OTh9.Hl2YC6UaaQM8cdTKjJ1wlARmBPB-F1n4EHdDq9q9xRo

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Kamal Jain",
    "password": "password",
    "email": "kamaltest@gmail.com"
}

###

POST http://localhost:3000/users/auth
Content-Type: application/json

{
    "email": "kamaltest@gmail.com",
    "password": "password"
}

###

POST http://localhost:3000/products
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAyMDM4NTI2LCJleHAiOjE2MDIwNDIxMjZ9.QFumyKQa_QPbhgBgG8Q-NCDhdShmHkj4n0BSdClW-JY

{
    "title": "T-shirt",
    "description": "One of the best tshirt in the market"
}

###

GET http://localhost:3000/products
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAxOTIxNTk4LCJleHAiOjE2MDE5MjUxOTh9.VIOkIOZjBk24a6WmPpDo_dhv5cxkmaXjIRVKPrOS9i8


###

GET http://localhost:3000/products/1
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAxOTIxNTk4LCJleHAiOjE2MDE5MjUxOTh9.VIOkIOZjBk24a6WmPpDo_dhv5cxkmaXjIRVKPrOS9i8

###

DELETE http://localhost:3000/products/1,2
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAxOTI1NTQ3LCJleHAiOjE2MDE5MjkxNDd9.ve4thMCyjGJRyVKlltCCuxP3-pfQjEJjilCc-Oz2GSE